accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.homepage, name='homepage'),

    path('signin', views.signin, name='signin'),
    path('signup', views.signup, name='signup'),
    path('signout', views.signout, name='signout'),

    path('user-profile', views.getProfile, name='user-profile'),
    path('update-user-profile', views.updateUserProfile, name='update-user-profile'),

    path('change-password', views.changePassword, name='change-password'),

    path('contact-us', views.contactUs, name='contact-us'),


    
]

books/urls.py
from django.urls import  path
from . import views

urlpatterns = [
    path('category-form', views.categoryForm, name='category-form'),
    path('get-category', views.getCategory, name='get-category'),
    path('delete-category/<int:category_id>', views.deleteCategory, name='delete-category'),
    path('update-category/<int:category_id>', views.categoryUpdateForm, name='update_category'),

    path('book-form', views.bookForm, name='book-form'),
    path('get-book', views.getBook, name='get-book'),
    path('delete-book/<int:book_id>', views.deleteBook, name='delete-book'),
    path('update-book/<int:book_id>', views.bookUpdateForm, name='update-book'),

    path('author-form', views.authorForm, name='author-form'),
    path('get-author', views.getAuthor, name='get-author'),
    path('delete-author/<int:author_id>', views.deleteAuthor, name='delete-author'),
    path('update-author/<int:author_id>', views.updateAuthor, name='update-author'),


    path('add-to-cart/<int:book_id>', views.addToCart, name="add-to-cart"),
    path('show-cart-items', views.showCartItems, name='show-cart-items'),
    path('remove-cart-items/<int:cart_id>', views.removeCartItems, name="remove-cart-items"),
    path('order-form/<int:book_id>/<int:cart_id>', views.orderForm),


    path('my-approved-order', views.approvedOrder, name='my-approved-order'),
    path('my-pending-order', views.pendingOrder, name='my-pending-order'),
    path('my-pending-order/cancel-order/<int:order_id>', views.cancelOrder),
    path('my-returned-order', views.returnedOrder,name='my-returned-order'),


    # URLs for User-Side
    path('show-categories-user', views.showCategories, name='show-categories-user'),
    path('show-books-user', views.showBooks, name='show-books-user'),
    path('show-authors-user', views.showAuthors, name='show-authors-user'),
    path('user-all-order', views.userAllOrder, name='user-all-order'),


]

elibrary/urls.py
from django.urls import include, path

urlpatterns = [
    path('', include('accounts.urls')),
    path('admins/', include('admins.urls')),
    path('books/', include('books.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import *
from django.core import validators
# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    forget_password_token = models.CharField(max_length=100, null=True)
    firstname = models.CharField(max_length=100, null=True)
    lastname = models.CharField(max_length=100, null=True)
    username = models.CharField(max_length=200, null=True)
    email = models.EmailField(null=True)
    phone = models.CharField(max_length=10, null=True)
    address = models.CharField(max_length=300, null=True)
    city = models.CharField(max_length=100,null=True)
    profile_pic = models.FileField(upload_to='static/uploads', default='static/images/user.png')
    created_date = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.username

class Contact(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    message = models.TextField(max_length=1000)
    date = models.DateTimeField(auto_now_add=True)
    class Meta:
        verbose_name_plural = "Contact"

    def __str__(self):
        return self.name + "-" +  self.email


class Author(models.Model):
    author_name = models.CharField(max_length=200, null=True, validators=[validators.MinLengthValidator(2)])
    firstname = models.CharField(max_length=50, null=True)
    lastname = models.CharField(max_length=50, null=True)
    email = models.EmailField(unique=True, null=True)
    profile_pic = models.FileField(upload_to='static/author_profile', null=True,
                                    default='static/user.png')
    created_date = models.DateField(auto_now_add=True, null=True)
    created_time = models.TimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.author_name

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile, Contact

class CreateUserForm(UserCreationForm):

    # Overriding usercreatiion form to design signup page
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({
            'required':'',
            'name':'username',
            'id':'username',
            'type':'text',
            'class':'form-input',
            'placeholder':'Username',
            'maxlength':'16',
            'minlength':'4',
        })
        self.fields['email'].widget.attrs.update({
            'required':'',
            'name':'email',
            'id':'email',
            'type':'email',
            'class':'form-input',
            'placeholder':'you@example.com',
            
        })
        self.fields['password1'].widget.attrs.update({
            'required':'',
            'name':'password1',
            'id':'password1',
            'type':'password',
            'class':'form-input',
            'placeholder':'********',
            'maxlength':'22',
            'minlength':'8',
        })
        self.fields['password2'].widget.attrs.update({
            'required':'',
            'name':'password2',
            'id':'password2',
            'type':'password',
            'class':'form-input',
            'placeholder':'********',
            'maxlength':'22',
            'minlength':'8',
        })
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['firstname','lastname','phone','address','city','profile_pic']

class ContactForm(forms.ModelForm):

    class Meta:
        model = Contact
        fields = '__all__'

accounts/views.py
from multiprocessing import context
from django.contrib.auth import authenticate,logout
from django.shortcuts import render, redirect
from django.contrib import messages

from books.models import Book, Cart
from .forms import CreateUserForm, ProfileForm, ContactForm
from django.contrib import auth
from accounts.auth import unauthenticated_user, user_only
from django.contrib.auth.decorators import login_required
from .models import Profile
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash

# To send mail to admin via contact form
from django.core.mail import mail_admins


def homepage(request):
    books = Book.objects.all().order_by('-id')[:7]
    if request.user.is_authenticated:
        user = request.user
        cart_items = Cart.objects.filter(user=user)
        cart_count = cart_items.count()
        
        context = {
            'cart_count': cart_count,
            'books': books,
        }
        return render(request, 'accounts/homepage.html', context)
        
    return render(request, 'accounts/homepage.html', {'books': books})
    

# @unauthenticated_user
def signin(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        
        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            auth.login(request, user)
            if user.is_superuser and user.is_staff and user.is_active:
                return redirect('/admins/dashboard')
            else:
                return redirect('/')
        else:
            messages.error(request, "Username or Password is incorrect.")
            return render(request, 'accounts/signin.html',{})
    context={
            'activate_login': 'active',
    }
    return render(request, 'accounts/signin.html',context)


# @unauthenticated_user
def signup(request):
    if request.method=='POST':
        userdata = CreateUserForm(request.POST)
        if userdata.is_valid():
            user=userdata.save()
            user.save()
            Profile.objects.create(user=user, username=user.username, email= user.email) 

            messages.add_message(request, messages.SUCCESS, f'{user.username} successfully registered to eLibrary.' )
            return redirect('/signin')
        else:
            context = {'form' : userdata}
            messages.add_message(request, messages.ERROR, 'Unable to register User!' )
            return render(request, 'accounts/signup.html',context)


    context ={
            'form' : CreateUserForm,
            'activate_register': 'active',
    }
    return render(request, 'accounts/signup.html', context)


# @login_required
def signout(request):
    logout(request)
    return redirect('/')


# @login_required
# @user_only
def getProfile(request):
    profile = request.user.profile
    user = request.user
    cart_items = Cart.objects.filter(user=user)
    cart_count = cart_items.count()
    
    context = {
        'profile': profile,
        'cart_count': cart_count,
        'activate_profile': 'active'
    }
    return render(request, 'accounts/userProfile.html', context)


# @login_required
# @user_only
def updateUserProfile(request):
    profile = request.user.profile
    user = request.user
    cart_items = Cart.objects.filter(user=user)
    cart_count = cart_items.count()
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, "Profile updated successfully")
            return redirect('/user-profile')
    context = {
        'profile': profile,
        'profileUpdateForm': ProfileForm(instance=profile),
        'cart_count': cart_count,
        'activate_profile': 'active'
    }
    return render(request, 'accounts/updateUserProfile.html', context)


# @login_required
# @user_only
def changePassword(request):
    user = request.user
    cart_items = Cart.objects.filter(user=user)
    cart_count = cart_items.count()
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.add_message(request, messages.SUCCESS, "Password Changed Successfully")
            return redirect('/change-password')
        else:
            messages.add_message(request, messages.ERROR, "Please verify the form fields")
            return redirect(request, 'accounts/changePassword.html', {'password_change_form': form})

    context = {
        'cart_count': cart_count,
        'password_change_form': PasswordChangeForm(request.user),

    }
    return render(request, 'accounts/changePassword.html', context)


def contactUs(request):
        if request.method == 'POST':
            f = ContactForm(request.POST)

            if f.is_valid():
                name = f.cleaned_data['name']
                sender = f.cleaned_data['email']
                subject = "You have a new Message from {}:{}".format(name, sender)
                message = "Message: {}".format(f.cleaned_data['message'])
                mail_admins(subject, message)
                f.save()
                messages.add_message(request, messages.SUCCESS, 'Your Message Submitted Successfully.')
                return redirect('/contact-us')

        else:
            f = ContactForm()
                
        return render(request, 'accounts/contactUs.html', {'form': f})

accounts/templates/accounts/changePassword.html
{% extends 'layout.html' %} {% load bootstrap %} {% load crispy_forms_tags %} {% block title %}
<title>Change Password | eLibrary</title>{% endblock%} {% block content %}
<style>
  .card-body {
    box-shadow: 0 0.5rem 1rem 0 rgba(0, 0, 0, 0.1);
  }
  .title {
    font-weight: 600;
  }

  .alert-danger {
    left: 25%;
    width: 50%;
  }

  ul {
    display: none;
  }

  #error_1_id_old_password,
  #error_1_id_new_password2 {
    display: none;
  }

  .col-lg-2 {
    width: auto !important;
  }
  .form-group,
  .custom-checkbox {
    margin-top: 1rem;
  }

  .form-group span {
    color: #dd4b39;
  }
</style>


<div style="margin-top: 2rem">
  <div class="container" style="margin-bottom: 3.7rem">
    <div class="row justify-content-center">
      <div class="col-lg-6 col-md-10 col-sm-10 my-auto">
        {% include 'message.html' %}
        <div class="card-body">
          <h4 class="title text-center px-4">Update Password</h4>
          <hr class="my-4" />
          <form method="POST" action="" class="form-box px-3">
            {% csrf_token %} {{password_change_form | crispy}}

            <div class="custom-control custom-checkbox">
              <input type="checkbox" class="custom-control-input" onclick="passwordToggle()" />
              <label class="custom-control-label" for="cb1">Show Password</label>
            </div>

            <button type="submit" class="btn btn-primary mt-3">Save Changes</button>
          </form>
        </div>
      </div>
    </div>
  </div>

  <script>
    function passwordToggle() {
      var x = document.getElementById("id_new_password1");
      var y = document.getElementById("id_new_password2");

      if (x.type === "password" && y.type == "password") {
        x.type = "text";
        y.type = "text";
      } else {
        x.type = "password";
        y.type = "password";
      }
    }

    var form_fields = document.getElementsByTagName("input");
    form_fields[1].placeholder = "******** ";
    form_fields[2].placeholder = "******** ";
    form_fields[3].placeholder = "******** ";

    for (var field in form_fields) {
      field.className += " form-control my-2";
    }
  </script>
  {% endblock %}
</div>

accounts/templates/accounts/contactUs.html
{% extends 'layout.html' %} {% load static %} {% block title %}
<title>Contact Us</title>
{% endblock %} {% block content %}

<style>
  .card-header i {
    color: #5bc3ee;
  }
  .card-header:hover i {
    transition: 0.8s all-ease-in-out;
    color: #4da3d6;
  }
  #user-data {
    outline: none;
    border-radius: 3px;
    border: 0;
    width: 100%;
    height: 45px;
    position: relative;
    border-bottom: 1px solid #b2b2b2;
    margin-bottom: 26px;
    line-height: 1.2;
    text-align: left;
    background: transparent;
    padding: 0 5px;
  }
  #message {
    outline: none;
    border-radius: 3px;
    border: 0;
    width: 100%;
    height: 150px;
    border-bottom: 1px solid #b2b2b2;
    margin-bottom: 26px;
    line-height: 1.2;
    text-align: left;
    background: transparent;
    padding: 0 5px;
  }
  #message:focus {
    border-bottom: 3px solid #ff0b0b;
  }
  #user-data:focus {
    border-bottom: 3px solid #5bc3ee;
  }
  #submit {
    border-radius: 5px;
    width: 12rem;
    background-color: #5bc3ee;
    color: #fff;
  }
  #submit:hover {
    background-color: #4da3d6;
  }
  #submit:hover i {
    -webkit-transform: translateX(10px);
    -moz-transform: translateX(10px);
    -ms-transform: translateX(10px);
    -o-transform: translateX(10px);
    transform: translateX(10px);
  }
</style>
<div class="container-fluid d-flex justify-content-center py-4">
  <div class="row">
    <div class="col-md-8 col-lg-8 col-xl-10 mx-auto">
{% include 'message.html' %}

      <div class="card shadow mt-4">
        <div class="card-header card-title text-center py-4">
          <h1>Contact Us</h1>
          <span class="py-4 mt-4">
            <a href="https://www.facebook.com/dipeshsiwakoti112" target="_blank"
              ><i class="fab fa-facebook-square fa-2x mt-4 mx-2"></i
            ></a>
            <a href="https://twitter.com/DipeshSiwakoti" target="_blank"
              ><i class="fab fa-twitter-square fa-2x mx-2"></i
            ></a>
            <a href="https://www.instagram.com/dipesh__siwakoti/" target="_blank"
              ><i class="fab fa-instagram-square fa-2x mx-2"></i
            ></a>
          </span>
        </div>
        <div class="card-body py-4">
          <form method="POST">
            {% csrf_token %}
            <input type="text" class="mt-4" name="name" id="user-data" placeholder="Your Name" />
            <input type="email" class="mt-2" name="email" id="user-data" placeholder="Your Email" />
            <textarea
              name="message"
              class="mt-2"
              placeholder="Your Message"
              id="message"
              cols="30"
              rows="10"
            ></textarea>

            <button type="submit" id="submit" class="btn py-2 px-2">
              SEND MESSAGE
              <i class="fa fa-long-arrow-right"></i>
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

accounts/templates/accounts/homepage.html
{% extends 'layout.html' %} {% load bootstrap %} {% load static %} {% block title %}

<title>Homepage | eLibrary</title>

{% endblock title %} {% block content %}

<div class="container-fluid p-0">
  <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button
        type="button"
        data-bs-target="#carouselExampleCaptions"
        data-bs-slide-to="0"
        class="active"
        aria-current="true"
        aria-label="Slide 1"
      ></button>
      <button
        type="button"
        data-bs-target="#carouselExampleCaptions"
        data-bs-slide-to="1"
        aria-label="Slide 2"
      ></button>
      <button
        type="button"
        data-bs-target="#carouselExampleCaptions"
        data-bs-slide-to="2"
        aria-label="Slide 3"
      ></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'images/carousel2.jpg' %}" class="d-block w-100" style="max-height: 700px" alt="..." />
        <div class="carousel-caption d-none d-md-block">
          <h5>Are you searching a book ?</h5>
          <h2>Biggest Library</h2>
          <p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/carousel1.jpg' %}" class="d-block w-100" style="max-height: 700px" alt="..." />
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/carousel3.jpg' %}" class="d-block w-100" style="max-height: 700px" alt="..." />
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>

<!-- Welcome Section -->
<center>
  <div class="container mb-4">
    <div class="section-heading-1">
      <h2 class="text-center mt-5 pt-2 p-3">What we offer?</h2>
    </div>
    <div class="row">
      <div class="card shadow border-0 mx-auto col-lg-3 col-md-3 col-sm-6 p-4 mt-2">
        <div class="card-center">
          <i class="fa fa-gift fa-4x hbook"></i>
          <h3 class="text-center">EBOOKS</h3>
          <p class="justify-content-between">An electronic version of a printed book that can be read on a computer.</p>
          <a href="#" class="btn btn-secondary read-more">Read More</a>
        </div>
      </div>
      <div class="card shadow border-0 mx-auto col-lg-3 col-md-3 col-sm-6 p-4 mt-2">
        <div class="card-center">
          <div class="kode-icon"><i class="fa fa-headphones fa-4x hbook" aria-hidden="true"></i></div>
          <h3 class="text-center mt-2">AUDIO BOOKS</h3>
          <p class="text-center">An audiocassette or CD recording of a reading of a book, typically a novel.</p>
          <a href="#" class="btn btn-secondary read-more">Read More</a>
        </div>
      </div>
      <div class="card shadow border-0 mx-auto col-lg-3 col-md-3 col-sm-6 p-4 mt-2">
        <div class="card-center">
          <div class="kode-icon"><i class="fa fa-book fa-4x hbook"></i></div>

          <h3 class="text-center mt-2">BOOKS</h3>
          <p class="text-center">A book is a medium for storing information in the form of writing.</p>
          <a href="#" class="btn btn-secondary read-more">Read More</a>
        </div>
      </div>
    </div>
  </div>
</center>

<!-- Recently featured -->

<section id="recently-added">
  <div class="best pt-5 mb-4">
    <div class="container">
      <div class="best-title text-center fs-1 mb-3">
        <h3 class="mb-4">Recently Added</h3>
      </div>

      <div id="owl-demo" class="owl-carousel owl-theme">
        {% for i in books %}
        <div class="card shadow">
          <div class="card-body item mb-4">
            <img
              src="/{{i.book_image}}"
              class="img-responsive card-img-top"
              height="475"
              width="auto"
              alt="Book Image"
              style="object-fit: cover"
            />
            <hr />
            <h4 class="card-title mt-3">{{i.book_name}}</h4>
            <span class="fa fa-star"></span>
            <span class="fa fa-star"></span>
            <span class="fa fa-star"></span>
            <span class="fa fa-star"></span>
            <span class="fa fa-star"></span>
            <p class="price mt-3">Rs. {{i.book_price}}</p>
            <p class="text-muted">{{i.category.category_name}}</p>

            <div id="cart-item" class="mb-4">
              <a
                href="/books/add-to-cart/{{i.id}}"
                class="btn btn-outline-primary"
                style="color: #5bc3ee; border-color: #5bc3ee"
                >Add to cart</a
              >
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</section>

<!-- Testimonials -->

<div id="eight">
  <div id="thirdhead">
    <div id="thirdheader">
      <h1 class="d-flex justify-content-center p-3 mt-0 text-white">Our Testimonials</h1>
    </div>
  </div>

  <div id="clients">
    <div class="client shadow border-0 text-white">
      <img
        src="{% static 'images/testimonial2.jpg' %}"
        style="width: 200px; height: 200px"
        class="img-responsive user-image"
        alt=""
      />
      <h2 class="text-white">Jennifer Willson</h2>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
      <p class="text-white p-2">
        "If you are looking for a rare book, you need to check out Parchment Bound Books on Main Street. I was looking
        for a first edition for my dad's birthday and I had almost given up.They have a huge selection of new, used and
        collectible books and their cappuccinos are to die for."
      </p>
    </div>
    <div class="client shadow border-0">
      <img src="{% static 'images/testimonial3.jpg' %}" style="width: 200px; height: 200px" alt="" />
      <h2 class="text-white">Orcand Keen</h2>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
      <p class="text-white p-2">
        "I went in just to see what they had and they were the friendliest people! They helped me find the perfect book
        for him and even offered a layaway."
      </p>
    </div>
    <div class="client shadow border-0">
      <img src="{% static 'images/testimonial1.jpg' %}" style="width: 200px; height: 200px" alt="" />
      <h2 class="text-white">Jack Killy</h2>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
      <p class="text-white p-2">
        "Jack Killy Our Client Lorem ipsum dolor sit amet, eiusmod tempor incididunt ut labore et consectetur adipiscing
        elit, sed do eiusmod tempor incididunt ut labore"
      </p>
    </div>
  </div>
</div>

{%endblock content %}

accounts/templates/accounts/signin.html
{% extends 'layout.html' %} {% load static %} {% load bootstrap %} {% load crispy_forms_tags %} {% block title %}
<title>Login</title>{% endblock %} {% block content %}

<style>
  body {
    font-family: Poppins;
  }
  .form-input {
    position: relative;
  }
  .form-input span {
    position: absolute;
    top: 11px;
    padding-left: 15px;
    color: #007bff;
  }
  .form-input input {
    padding-left: 35px;
  }
  .form-input input::placeholder {
    padding-left: 5px;
  }

  .forget-link,
  .register-link {
    color: #007bff;
    font-weight: 500;
    text-decoration: none;
  }

  .forget-link:hover,
  .register-link:hover {
    color: #0069d9;
    text-decoration: underline;

  }
</style>

<section class="vh-100" style="background-color: #508bfc">
  <div class="container py-2 h-100">
    <div class="row d-flex justify-content-center align-items-center mt-4">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        {% include 'message.html'%}

        <div class="card shadow-2-strong" style="border-radius: 1rem">
          <div class="card-body p-4">
            <div class="d-flex justify-content-center">
              <img class="mt-0" src="{% static 'images/elibtransparent.png' %}" alt="" />
            </div>
            <form method="POST" class="form-box px-3">
              {%csrf_token%}
              <div class="form-input form-outline mb-4">
                <span><i class="fa fa-user fa-sm" aria-hidden="true"></i></span>
                <input
                  type="text"
                  id="username"
                  name="username"
                  placeholder="Username"
                  class="form-control form-control-lg"
                />
              </div>

              <div class="form-input form-outline mb-4">
                <span><i class="fa fa-lock fa-sm" aria-hidden="true"></i></span>

                <input
                  type="password"
                  id="password"
                  name="password"
                  placeholder="********"
                  class="form-control form-control-lg"
                />
              </div>

              <!-- Checkbox -->
              <div class="d-flex justify-content-between mb-2">
                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" onclick="passwordToggle()" />
                  <label class="custom-control-label" for="cb1">Show Password</label>
                </div>

              </div>

              <div class="mb-4 ">
                <button class="btn btn-primary btn-block text-center text-uppercase w-100 py-2 mt-4" type="submit">Login</button>
                <hr class="my-4" />
                </div>
              <div class="text-center">
                <label class="form-check-label" for="form1Example3">Don't have and account? </label>
                <a href="/signup" class="ml-2 register-link">Sign Up</a>
              </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<script>
  function passwordToggle() {
    var x = document.getElementById("password");

    if (x.type === "password") {
      x.type = "text";
    } else {
      x.type = "password";
    }
  }
</script>

{% endblock %}

accounts/templates/accounts/updateUserProfile.html
{% extends 'layout.html' %} {% load static %} {% load bootstrap %} {% load crispy_forms_tags %}{% block title %}

<title>Update Profile | eLibrary</title>

{% endblock title %} {% block content %}

<style>
  body {
    font-family: Poppins;
  }
  .container {
    outline: none;
  }
  .card {
    position: unset !important;
    box-shadow: 0 2px 10px rgb(0 22 84 / 10%);
  }

  .card-body {
    padding: 1.5rem;
    flex: 1 1 auto;
  }

  .requiredField {
    font-weight: 600;
    font-family: "Manrope", sans-serif;
    font-size: 16px;
    color: #242f65;
  }
  #id_firstname,
  #id_lastname,
  #id_phone,
  #id_address,
  #id_city,
  #id_profile_pic {
    color: #70798b;
    font-weight: 400;
    font-family: "Manrope", sans-serif;
    font-size: 16px;
  }

  #div_id_firstname,
  #div_id_lastname,
  #div_id_phone,
  #div_id_address,
  #div_id_city,
  #div_id_profile_pic {
    margin: 1em;
  }

  .form-group span {
    color: #dd4b39;
  }
</style>

<div class="container mb-5 mt-5">
  <h1 class="text-center mb-5">
    Update Profile
  </h1>
  <div class="row">
    <div class="col-md-6 offset-md-3">
      {% include 'message.html' %}
      <div class="card form-box-shadow py-4 px-4">
        <form class="form " action="" method="POST" enctype="multipart/form-data">
          {% csrf_token %} {{ profileUpdateForm|crispy }}
          <button type="submit" class="btn btn-primary mt-3">Submit</button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock content %}